Use Scala code to decode PGP_SECRET
ckipp01/mill-ci-release pull request #41
Opened 2023-01-19 13:17 UTC by nightscape

Fixes #40

2023-01-19 14:02 UTC, ckipp01 requested changes
Thanks @nightscape! So even on windows though, won't you still have issues with some of the other methods being used like `gpg`, or will that actually be available to you?

2023-01-19 14:02 UTC, ckipp01 commented on plugin/src/io/kipp/mill/ci/release/CiReleaseModule.scala
> +      val decoded = new String(Base64.getDecoder.decode(pgpSecret.getBytes(StandardCharsets.UTF_8)))
So I think if we're going to move into Scala-land here we should probably start also catching stuff that can throw. We should probably wrap this in a try here to catch the exception that could happen in `decode` if it's not a valid base64 encoded string.

2023-01-19 14:08 UTC, nightscape commented
I have `gpg` available. Not sure atm if it was available by default, or if I installed it myself.

2023-01-19 14:19 UTC, ckipp01 commented on plugin/src/io/kipp/mill/ci/release/CiReleaseModule.scala
> +      val decoded = new String(Base64.getDecoder.decode(pgpSecret.getBytes(StandardCharsets.UTF_8)))
What I'd recommend is wrapping the entire thing in a try and catch the `IllegalArgumentException`. Something like this:

```scala
      try {
        val decoded = new String(
          Base64.getDecoder.decode(pgpSecret.getBytes(StandardCharsets.UTF_8))
        )

        // https://dev.gnupg.org/T2313
        val imported = os
          .proc("gpg", "--batch", "--import", "--no-tty")
          .call(stdin = decoded)

        if (imported.exitCode != 0)
          Result.Failure(
            "Unable to import your pgp key. Make sure your secret is correct."
          )
      } catch {
        case e: IllegalArgumentException =>
          Result.Failure(
            s"Invalid secrete, unable to decode it: ${e.getMessage()}"
          )
        case e: Throwable => Result.Failure(e.getMessage())
      }
```

2023-01-20 11:07 UTC, nightscape commented on plugin/src/io/kipp/mill/ci/release/CiReleaseModule.scala
> +      val decoded = new String(Base64.getDecoder.decode(pgpSecret.getBytes(StandardCharsets.UTF_8)))
Looks good!
Should the `case e: Throwable` be a `case e: Exception`?
Afair, one should not catch `Throwable`.

2023-01-20 11:48 UTC, nightscape commented
@ckipp01 how about the new version?
Not sure if you like the `Either`-based for-comprehension?

2023-01-20 13:17 UTC, ckipp01 commented on plugin/src/io/kipp/mill/ci/release/CiReleaseModule.scala
> +      val decoded = new String(Base64.getDecoder.decode(pgpSecret.getBytes(StandardCharsets.UTF_8)))
Correct, this was quickly pseudo-coded. As an alternative we can probably catch `NonFatal(e)` here.

2023-02-07 16:16 UTC, nightscape commented
I just added code that removes whitespaces from the `PGP_SECRET`, otherwise the Base64 decoder breaks e.g. on new-lines.

2023-02-07 16:52 UTC, ckipp01 commented on plugin/src/io/kipp/mill/ci/release/CiReleaseModule.scala
> +    val pgpSecret = envTask().pgpSecret.replaceAll("\\s", "")
Would trim do the same thing here?

2023-02-08 11:45 UTC, nightscape commented on plugin/src/io/kipp/mill/ci/release/CiReleaseModule.scala
> +    val pgpSecret = envTask().pgpSecret.replaceAll("\\s", "")
Just tested this in Ammonite, and `trim` only seems to remove leading and trailing spaces:
```scala
" foo bar baz\t".trim // => "foo bar baz"
```
PGP_SECRETS often consist of multiple lines which would not be covered by `trim`.

2023-02-17 11:36 UTC, nightscape commented
@ckipp01 this is good to merge from my side 😃

2023-03-10 13:44 UTC, ckipp01 approved these changes
Hey @nightscape, sorry for the delay on this. Things got a bit hectic and I've put it off. Let's give it a go. If something seems off, we can just revert. Thanks again for your work on this.

2023-03-10 13:44 UTC, merged